version: '3'

services:
    gossip:
        build: .
        container_name: gossip
        restart: always

        environment:
            - IP_SERVICE_PORT=10059

#        Or .env
#        env_file:
#            -   ".env"

        ports:
            - '${IP_SERVICE_PORT}:${IP_SERVICE_PORT}'
